VietGearStore.1511060754/Controllers/GlobalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VietGearStore._1511060754.Models;

namespace VietGearStore._1511060754.Controllers
{
    public class GlobalController : Controller
    {
        datalinhkienEntities _db = new datalinhkienEntities();
        // GET: Global
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult getMenu()
        {
            var v = from t in _db.Menus
                    where t.hide == true
                    orderby t.order ascending
                    select t;
            return PartialView(v.ToList());
        }
        public ActionResult getMenuLeft()
        {
            var v = from t in _db.Categories
                    where t.hide == true
                    orderby t.order ascending
                    select t;
            return PartialView(v.ToList());
        }
        public ActionResult getLienlac()
        {
            var v = from t in _db.Lienlacs
                    where t.hide == true
                    orderby t.order ascending
                    select t;
            return PartialView(v.ToList());
        }
        public ActionResult getInfo()
        {
            var v = from t in _db.Infoes
                    where t.hide == true
                    orderby t.order ascending
                    select t;
            return PartialView(v.ToList());
        }
        public ActionResult getSlide()
        {
            var v = from t in _db.Slides
                    where t.hide == true
                    orderby t.order ascending
                    select t;
            return PartialView(v.ToList());
        }
        public ActionResult getLogo()
        {
            var v = from t in _db.Logoes
                    where t.hide == true
                    orderby t.order ascending
                    select t;
            return PartialView(v.ToList());
        }
    }
}

VietGearStore.1511060754/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VietGearStore._1511060754.Models;

namespace VietGearStore._1511060754.Controllers
{
    public class LoginController : Controller
    {
        datalinhkienEntities db = new datalinhkienEntities();
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(FormCollection collection)
        {
            // Gán các giá trị người dùng nhập liệu cho các biến 
            var tendn = collection["username"];
            var matkhau = collection["password"];
            if (String.IsNullOrEmpty(tendn))
            {
                ViewData["Loi1"] = "Phải nhập tên đăng nhập";
            }
            else if (String.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi2"] = "Phải nhập mật khẩu";
            }
            else
            {
                //Gán giá trị cho đối tượng được tạo mới (ad)        

                Admin ad = db.Admins.SingleOrDefault(n => n.UserAdmin == tendn && n.PassAdmin == matkhau);
                if (ad != null)
                {
                    // ViewBag.Thongbao = "Chúc mừng đăng nhập thành công";
                    Session["Taikhoanadmin"] = ad;
                    return RedirectToAction("Index", "admin");
                }
                else
                    ViewBag.Thongbao = "Tên đăng nhập hoặc mật khẩu không đúng";
            }
            return View();
        }
    }
}

VietGearStore.1511060754/Views/Shared/Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Linh kiện máy tính</title>
    <meta name="keywords" content="@ViewBag.Keyword - Linh kiện máy tính,gear,phụ kiện máy tính,phần cứng máy tính" />
    <link href="~/Content/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <link href="~/Content/css/slider.css" rel="stylesheet" type="text/css" media="all" />
    <script type="text/javascript" src="~/Scripts/js/jquery-1.7.2.min.js"></script>
    <script type="text/javascript" src="~/Scripts/js/move-top.js"></script>
    <script type="text/javascript" src="~/Scripts/js/easing.js"></script>
    <script type="text/javascript" src="~/Scripts/js/startstop-slider.js"></script>
</head>
<body>
    <div class="wrap">
        <div class="header">
            <div class="headertop_desc">
                <div class="call">
                    <p>HOTLINE: <span class="number">0927056456</span></p>
                </div>
                <div class="account_desc">
                    <ul>
                        <li><a href="#">Đăng kí</a></li>
                        <li><a href="@Url.Action("Index","Login")">Đăng nhập</a></li>
                        <li><a href="#">Tài khoản của tôi</a></li>
                    </ul>
                </div>
                <div class="clear"></div>
            </div>
            <div class="header_top">
                <div class="logo">
                    @{ Html.RenderAction("getLogo", "Global");}
                </div>
                <div class="cart">
                    <p>
                        <span>GIỎ HÀNG:</span><div id="dd" class="wrapper-dropdown-2">
                            0 item(s) - $0.00
                            <ul class="dropdown"></ul>
                        </div>
                    </p>
                </div>
                <script type="text/javascript">
                    function DropDown(el) {
                        this.dd = el;
                        this.initEvents();
                    }
                    DropDown.prototype = {
                        initEvents: function () {
                            var obj = this;

                            obj.dd.on('click', function (event) {
                                $(this).toggleClass('active');
                                event.stopPropagation();
                            });
                        }
                    }

                    $(function () {

                        var dd = new DropDown($('#dd'));

                        $(document).click(function () {
                            // all dropdowns
                            $('.wrapper-dropdown-2').removeClass('active');
                        });

                    });

                </script>
                <div class="clear"></div>
            </div>
            <div class="header_bottom">
                <div class="menu">
                    <ul>
                        @{ Html.RenderAction("getMenu", "Global");}
                    </ul>
                </div>
                <div class="search_box">
                    <form>
                        <input type="text" value="Search" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search';}"><input type="submit" value="">
                    </form>
                </div>
                <div class="clear"></div>
            </div>
            <div class="header_slide">
                <div class="header_bottom_left">
                </div>
                <div class="header_bottom_right">
                </div>
                <div class="clear"></div>
            </div>
        </div>
        <div class="main">
            @RenderBody()
        </div>
    </div>
    <div class="footer">
        <div class="wrap">
            <div class="section group">
                <div class="col_1_of_4 span_1_of_4">
                    <h4>THÔNG TIN</h4>
                    <ul>
                        @{ Html.RenderAction("getInfo", "Global");}
                    </ul>
                </div>
                <div class="col_1_of_4 span_1_of_4">
                    <h4>LIÊN HỆ</h4>
                    <ul>
                        @{ Html.RenderAction("getLienlac", "Global");}
                    </ul>
                </div>
                <div class="col_1_of_4 span_1_of_4">
                    <iframe width="200" height="200" src="https://www.youtube.com/embed/xGWGTneITus" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
                </div>
                <div class="col_1_of_4 span_1_of_4">
                    <iframe src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2Ffacebook&tabs=timeline&width=350&height=200&small_header=true&adapt_container_width=true&hide_cover=false&show_facepile=true&appId" width="200" height="200" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true" allow="encrypted-media"></iframe>
                </div>
            </div>
        </div>
        <div class="copy_right">
            <p>Design by Phan Xuan </p>
        </div>
    </div>
    <script type="text/javascript">
        $(document).ready(function () {
            $().UItoTop({ easingType: 'easeOutQuart' });

        });
    </script>
    
    <link type='text/css' rel='stylesheet' href='https://nguyenhungplus.com/chat-fb/style.css' />
    <script type='text/javascript' src='https://nguyenhungplus.com/chat-fb/jquery.event.move.js'></script>
    <script type='text/javascript' src='https://nguyenhungplus.com/chat-fb//rebound.min.js'></script>
    <script type='text/javascript' src='https://nguyenhungplus.com/chat-fb/index.js'></script>
</body>
</html>

VietGearStore.1511060754/Views/Shared/MyLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Linh kiện máy tính</title>
    <meta name="keywords" content="@ViewBag.Keyword - Linh kiện máy tính,gear,phụ kiện máy tính,phần cứng máy tính" />
    <link href="~/Content/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <link href="~/Content/css/slider.css" rel="stylesheet" type="text/css" media="all" />
    <script type="text/javascript" src="~/Scripts/js/jquery-1.7.2.min.js"></script>
    <script type="text/javascript" src="~/Scripts/js/move-top.js"></script>
    <script type="text/javascript" src="~/Scripts/js/easing.js"></script>
    <script type="text/javascript" src="~/Scripts/js/startstop-slider.js"></script>
</head>
<body>
    <div class="wrap">
        <div class="header">
            <div class="headertop_desc">
                <div class="call">
                    <p>HOTLINE: <span class="number">0927056456</span></p>
                </div>
                <div class="account_desc">
                    <ul>
                        <li><a href="#">Đăng kí</a></li>
                        <li><a href="@Url.Action("Index","Login")">Đăng nhập</a></li>
                        <li><a href="#">Tài khoản của tôi</a></li>
                    </ul>
                </div>
                <div class="clear"></div>
            </div>
            <div class="header_top">
                <div class="logo">
                    @{ Html.RenderAction("getLogo", "Global");}
                </div>
                <div class="cart">
                    <p>
                        <span>GIỎ HÀNG:</span><div id="dd" class="wrapper-dropdown-2">
                            0 item(s) - $0.00
                            <ul class="dropdown"></ul>
                        </div>
                    </p>
                </div>
                <script type="text/javascript">
                    function DropDown(el) {
                        this.dd = el;
                        this.initEvents();
                    }
                    DropDown.prototype = {
                        initEvents: function () {
                            var obj = this;

                            obj.dd.on('click', function (event) {
                                $(this).toggleClass('active');
                                event.stopPropagation();
                            });
                        }
                    }

                    $(function () {

                        var dd = new DropDown($('#dd'));

                        $(document).click(function () {
                            // all dropdowns
                            $('.wrapper-dropdown-2').removeClass('active');
                        });

                    });

                </script>
                <div class="clear"></div>
            </div>
            <div class="header_bottom">
                <div class="menu">
                    <ul>
                        @{ Html.RenderAction("getMenu", "Global");}
                    </ul>
                </div>
                <div class="search_box">
                    <form>
                        <input type="text" value="Search" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search';}"><input type="submit" value="">
                    </form>
                </div>
                <div class="clear"></div>
            </div>
            <div class="header_slide">
                <div class="header_bottom_left">
                    <div class="categories">
                        <h3>DANH MỤC</h3>
                        <ul>
                            @{ Html.RenderAction("getMenuLeft", "Global");}
                        </ul>
                    </div>
                </div>
                <div class="header_bottom_right">
                    <div class="slider">
                        @{ Html.RenderAction("getSlide", "Global");}
                        <div class="clear"></div>
                    </div>
                </div>
                <div class="clear"></div>
            </div>
        </div>
        <div class="main">
            @RenderBody()
        </div>
    </div>
    <div class="footer">
        <div class="wrap">
            <div class="section group">
                <div class="col_1_of_4 span_1_of_4">
                    <h4>THÔNG TIN</h4>
                    <ul>
                        @{ Html.RenderAction("getInfo", "Global");}
                    </ul>
                </div>
                <div class="col_1_of_4 span_1_of_4">
                    <h4>LIÊN LẠC</h4>
                    <ul>
                        @{ Html.RenderAction("getLienlac", "Global");}
                    </ul>
                </div>
                <!--<div class="col_1_of_4 span_1_of_4">
                    <iframe width="200" height="200" src="https://www.youtube.com/embed/xGWGTneITus" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
                </div>
                <div class="col_1_of_4 span_1_of_4">
                    <iframe src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2Ffacebook&tabs=timeline&width=350&height=200&small_header=true&adapt_container_width=true&hide_cover=false&show_facepile=true&appId" width="200" height="200" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true" allow="encrypted-media"></iframe>
                </div>-->
            </div>
        </div>
        <div class="copy_right">
            <p> Design by  ** </p>
        </div>
    </div>
    <script type="text/javascript">
        $(document).ready(function () {
            $().UItoTop({ easingType: 'easeOutQuart' });

        });
    </script>
   <!-- <a href="#" id="toTop"><span id="toTopHover"> </span></a>
    <div class="drag-wrapper drag-wrapper-right">
        <div data-drag="data-drag" class="thing">
            <div class="circle facebook-messenger-avatar facebook-messenger-avatar-type0">
                <img class="facebook-messenger-avatar" src="https://nguyenhungplus.com/chat-fb/facebook-messenger.svg" />
            </div>
            <div class="content">
                <div class="inside">
                    <div class="fb-page" data-width="310" data-height="310" data-href="https://www.facebook.com/CarShop_1511060244-430302940746026" data-tabs="messages" data-small-header="true" data-hide-cover="false" data-show-facepile="true" data-adapt-container-width="true"><div class="fb-xfbml-parse-ignore"><blockquote cite="https://www.facebook.com/blogcongdongcom"><a href="https://www.facebook.com/blogcongdongcom">Loading...</a></blockquote></div></div>
                </div>
            </div>
        </div>
        <div class="magnet-zone">
            <div class="magnet"></div>
        </div>
    </div>-->
    <link type='text/css' rel='stylesheet' href='https://nguyenhungplus.com/chat-fb/style.css' />
    <script type='text/javascript' src='https://nguyenhungplus.com/chat-fb/jquery.event.move.js'></script>
    <script type='text/javascript' src='https://nguyenhungplus.com/chat-fb//rebound.min.js'></script>
    <script type='text/javascript' src='https://nguyenhungplus.com/chat-fb/index.js'></script>
</body>
</html>

VietGearStore.1511060754/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>