VietGearStore.1511060754/Models/Lienhe.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietGearStore._1511060754.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lienhe
    {
        public int id { get; set; }
        public string name { get; set; }
        public string gmail { get; set; }
        public string description { get; set; }
        public string detail { get; set; }
        public Nullable<System.DateTime> datebegin { get; set; }
    }
}

VietGearStore.1511060754/Areas/admin/Controllers/LienhesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VietGearStore._1511060754.Models;

namespace VietGearStore._1511060754.Areas.admin.Controllers
{
    public class LienhesController : Controller
    {
        private datalinhkienEntities db = new datalinhkienEntities();

        // GET: admin/Lienhes
        public ActionResult Index()
        {
            return View(db.Lienhes.ToList());
        }

        // GET: admin/Lienhes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lienhe lienhe = db.Lienhes.Find(id);
            if (lienhe == null)
            {
                return HttpNotFound();
            }
            return View(lienhe);
        }

        // GET: admin/Lienhes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: admin/Lienhes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name,gmail,description,detail,datebegin")] Lienhe lienhe)
        {
            if (ModelState.IsValid)
            {
                db.Lienhes.Add(lienhe);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(lienhe);
        }

        // GET: admin/Lienhes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lienhe lienhe = db.Lienhes.Find(id);
            if (lienhe == null)
            {
                return HttpNotFound();
            }
            return View(lienhe);
        }

        // POST: admin/Lienhes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,name,gmail,description,detail,datebegin")] Lienhe lienhe)
        {
            if (ModelState.IsValid)
            {
                db.Entry(lienhe).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(lienhe);
        }

        // GET: admin/Lienhes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lienhe lienhe = db.Lienhes.Find(id);
            if (lienhe == null)
            {
                return HttpNotFound();
            }
            return View(lienhe);
        }

        // POST: admin/Lienhes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Lienhe lienhe = db.Lienhes.Find(id);
            db.Lienhes.Remove(lienhe);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

VietGearStore.1511060754/Controllers/LienheController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VietGearStore._1511060754.Models;

namespace VietGearStore._1511060754.Controllers
{
    public class LienheController : Controller
    {
        private datalinhkienEntities db = new datalinhkienEntities();

        // GET: Lienhes
        public ActionResult Create()
        {
            return View();
        }
        // POST: Lienhes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name,gmail,description,detail,datebegin")] Lienhe lienhe)
        {
            if (ModelState.IsValid)
            {
                lienhe.datebegin = Convert.ToDateTime(DateTime.Now.ToShortDateString());
                db.Lienhes.Add(lienhe);
                db.SaveChanges();
                return RedirectToAction("Create");
            }

            return View(lienhe);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

VietGearStore.1511060754/Areas/admin/Views/Lienhes/Delete.cshtml
@model VietGearStore._1511060754.Models.Lienhe

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-red">
            <div class="panel-heading">
                Xóa thông tin liên hệ từ khách hàng
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">

                <h3>Bạn muốn xóa thông tin liên hệ này?</h3>
                <div>

                    <hr />
                    <dl class="dl-horizontal">
                        <dt>
                            Họ tên
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.name)
                        </dd>

                        <dt>
                            Gmail
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.gmail)
                        </dd>

                        <dt>
                            Tiêu đề
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.description)
                        </dd>

                        <dt>
                            Nội dung
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.detail)
                        </dd>

                    </dl>

                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-actions no-color">
                            <input type="submit" value="Xóa" class="btn btn-danger" /> |
                            @Html.ActionLink("Quay lại", "Index")
                        </div>
                    }
                </div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

VietGearStore.1511060754/Areas/admin/Views/Lienhes/Details.cshtml
@model VietGearStore._1511060754.Models.Lienhe

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-red">
            <div class="panel-heading">
                Chi tiết thông tin liên hệ từ khách hàng
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <dl class="dl-horizontal">
                    <dt>
                        Họ tên
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.name)
                    </dd>

                    <dt>
                        Gmail
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.gmail)
                    </dd>

                    <dt>
                        Tiêu đề
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.description)
                    </dd>

                    <dt>
                        Nội dung
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.detail)
                    </dd>
                </dl>
            </div>
            <p>
                @Html.ActionLink("Quay lại", "Index")
            </p>
        </div>
        <!-- /.panel-body -->
    </div>
    <!-- /.panel -->
</div>
<!-- /.col-lg-12 -->
@section _Footer
{
    <script src="~/Areas/admin/Content/ckfinder/ckfinder.js"></script>
    <script src="~/Areas/admin/Content/ckeditor/ckeditor.js"></script>
    <script type="text/javascript">
        var editor = CKEDITOR.replace("detail");
        var editor = CKEDITOR.replace("detail", { height: '600px' });
        customConfig: '/Areas/admin/Content/ckeditor/config.js';
    </script>
    <script>
        $(function () {
            $("#name").keyup(function () {
                var text = $.trim($(this).val().toLowerCase());
                var text_create;
                text_create = text.replace(/à|á|ạ|ả|ã|â|ầ|ấ|ậ|ẩ|ẫ|ă|ằ|ắ|ặ|ẳ|ẵ/g, "a").replace(/\ /g, '-').replace(/đ/g, "d").replace(/đ/g, "d").replace(/ỳ|ý|ỵ|ỷ|ỹ/g, "y").replace(/ù|ú|ụ|ủ|ũ|ư|ừ|ứ|ự|ử|ữ/g, "u").replace(/ò|ó|ọ|ỏ|õ|ô|ồ|ố|ộ|ổ|ỗ|ơ|ờ|ớ|ợ|ở|ỡ.+/g, "o").replace(/è|é|ẹ|ẻ|ẽ|ê|ề|ế|ệ|ể|ễ.+/g, "e").replace(/ì|í|ị|ỉ|ĩ/g, "i");
                $('#meta').val(text_create);
            }).keyup();
        });
    </script>
}

VietGearStore.1511060754/Areas/admin/Views/Lienhes/Index.cshtml
@using VietGearStore._1511060754.Help
@model IEnumerable<VietGearStore._1511060754.Models.Lienhe>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}

<style>
    th, td {
        text-align: center;
    }

        td p {
            height: 50px;
            overflow-y: hidden;
            text-overflow: ellipsis;
        }
</style>

@section _Header
{
    <!-- DataTables CSS -->
    <link href="/Areas/admin/Content/vendor/datatables-plugins/dataTables.bootstrap.css" rel="stylesheet">
    <!-- DataTables Responsive CSS -->
    <link href="/Areas/admin/Content/vendor/datatables-responsive/dataTables.responsive.css" rel="stylesheet">

}
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-red">
            <div class="panel-heading">
                Quản lý thông tin liên lạc
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <table class="table table-striped table-bordered table-hover" id="dataTables-example" style="width:100%">
                    <thead>
                        <tr>
                            <th>
                                STT
                            </th>
                            <th>
                                Họ tên
                            </th>
                            <th>
                                Gmail
                            </th>
                            <th>
                                Tiêu đề
                            </th>
                            <th>
                                Nội dung
                            </th>
                            <th></th>
                        </tr>

                    </thead>
                    <tbody>
                        @{var Number = 1; }
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.Raw(Number++)
                                </td>
                                <td style="text-align:left; white-space:nowrap">
                                    @Html.DisplayFor(modelItem => item.name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.gmail)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.description)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.detail)
                                </td>
                                <td>
                                    @Html.NoEncodeActionLink("<span class='glyphicon glyphicon-zoom-in'></span>", "Detail", "Details", "Lienhes", routeValues: new { id = item.id }, htmlAttributes: new { data_modal = "", @class = "btn btn-primary" })
                                    @Html.NoEncodeActionLink("<span class='glyphicon glyphicon-trash'></span>", "Delete", "Delete", "Lienhes", routeValues: new { id = item.id }, htmlAttributes: new { data_modal = "", @class = "btn btn-danger" })
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
@section _Footer
{
    <!-- DataTables JavaScript -->
    <script src="/Areas/admin/Content/vendor/datatables/js/jquery.dataTables.min.js"></script>
    <script src="/Areas/admin/Content/vendor/datatables-plugins/dataTables.bootstrap.min.js"></script>
    <script src="/Areas/admin/Content/vendor/datatables-responsive/dataTables.responsive.js"></script>
    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
        $(document).ready(function () {
            $('#dataTables-example').DataTable({
                responsive: true
            });
        });
    </script>

}